In [1]:
import glob
import os
os.chdir('..')

In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd

# 1. Import

In [3]:
# Path to the data folder
folder = 'data/raw'

# Define the common
source_name = 'establishments'

# Use glob to find all the filepaths that start with "udalmap"
filepaths = glob.glob(os.path.join(folder, source_name) + '*.csv')
print(filepaths)

['data/raw\\establishments-2014.csv', 'data/raw\\establishments-2016.csv', 'data/raw\\establishments-2018.csv', 'data/raw\\establishments-2020.csv', 'data/raw\\establishments-2022.csv', 'data/raw\\establishments-2024.csv']

In [4]:
## Import the establishments datasets into a single DataFrame
df_list = []
for filepath in filepaths:
    path = os.path.abspath(filepath)
    file_name = os.path.basename(filepath) # get only the file name without the path
    year = int(file_name.replace(source_name, '').replace('-', '').replace('.csv', '')) # get the description of the data

    data = pd.read_csv(path, sep=';', decimal=',', index_col=None, encoding='latin-1')
    print(f'The file {path} has been imported')

    data['Year'] = year

    df_list.append(data) # add the processed data to the list
    
# Concatenate all the datasets from udalmap
df_combined = pd.concat(df_list, axis=0, join='inner')
df_combined

The file c:\Users\narronizari\OneDrive - ---\Escritorio\phd-research\data\raw\establishments-2014.csv has been imported
The file c:\Users\narronizari\OneDrive - ---\Escritorio\phd-research\data\raw\establishments-2016.csv has been imported
The file c:\Users\narronizari\OneDrive - ---\Escritorio\phd-research\data\raw\establishments-2018.csv has been imported

C:\Users\narronizari\AppData\Local\Temp\ipykernel_25776\2625544219.py:8: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(path, sep=';', decimal=',', index_col=None, encoding='latin-1')

The file c:\Users\narronizari\OneDrive - ---\Escritorio\phd-research\data\raw\establishments-2020.csv has been imported
The file c:\Users\narronizari\OneDrive - ---\Escritorio\phd-research\data\raw\establishments-2022.csv has been imported

C:\Users\narronizari\AppData\Local\Temp\ipykernel_25776\2625544219.py:8: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(path, sep=';', decimal=',', index_col=None, encoding='latin-1')

The file c:\Users\narronizari\OneDrive - ---\Escritorio\phd-research\data\raw\establishments-2024.csv has been imported

,Código de establecimiento,Denominación de establecimiento,Dirección de establecimiento,Aproximación postal del establecimiento,Complemento de dirección del establecimiento,Código postal,TH,Comar,Mun,Distrito,...,COMARCA,PROVINCIA,CNAE EMPRESA,NUM ESTABL,EMPLEMP,Teléfono1 emp,coordenada x emp,coordenada y emp,Correo electrónico empresa,Year
0,L0000074,CAF,"CL Jose Migel Iturriotz, 26, Bajo",NaN,NaN,20200.0,20,5.0,19.0,1.0,...,Goierri,Gipuzkoa,3020.0,2.0,10.0,943880100.0,566017.911586412,4766769.637825750,caf@caf.net,2014
1,L0000075,CAF,"CL Anaca, 13, Bajo",NaN,NaN,20301.0,20,1.0,45.0,3.0,...,Goierri,Gipuzkoa,3020.0,2.0,10.0,943880100.0,566017.911586412,4766769.637825750,caf@caf.net,2014
2,L0000084,Goenaga,"BA Elbarrena, 7, Bajo",NaN,NaN,20247.0,20,5.0,78.0,1.0,...,Goierri,Gipuzkoa,4672.0,1.0,3.0,943880663.0,569178.939505614,4765813.062533880,NaN,2014
3,L0000090,Aquarbe,"PL Euskadi, 6, Bajo",NaN,NaN,20700.0,20,5.0,80.0,1.0,...,Bilbo Handia/Gran Bilbao,Bizkaia,3600.0,7.0,7.0,944766040.0,504161.487961797,4791001.105580570,NaN,2014
4,L0000105,Ayestaran Ferreteria,"CL Aldakonea, 6, Bajo, 2",NaN,NaN,20012.0,20,4.0,69.0,4.0,...,Donostialdea/Donostia-San Sebastián,Gipuzkoa,4674.0,1.0,2.0,NaN,583245.088260498,4796927.229335210,NaN,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55461,L0555725,Norbide,"PS Lazkano, 5, 1º, Mano B",NaN,NaN,20009.0,20,4.0,69.0,3.0,...,Enkartazioak / Encartaciones,Bizkaia,8299.0,2.0,6.0,946800490.0,484220.546208971,4782542.467311920,NaN,2024
55462,L0555726,Limpiezas Soldene,"PL Julio Caro Baroja, 2, Bajo",NaN,Jefatura Provincial de Tráfico de Gipuzkoa,20018.0,20,4.0,69.0,6.0,...,NaN,Madrid,8121.0,3.0,6.0,913274354.0,.,.,soldene@soldene.es,2024
55463,L0555727,Asoc. Benefica Asistencial Elkarbanatuz,"AV Elizatxo, 14, Bajo",NaN,NaN,20303.0,20,1.0,45.0,3.0,...,Bilbo Handia / Gran Bilbao,Bizkaia,9499.0,5.0,7.0,944757643.0,503604.613113108,4790834.529486650,administracion@elkarbanatuz.org,2024
55464,L0555731,Fontanería,"BA Artzalluz, 3, Bajo",NaN,Zuazketa Baserria,20737.0,20,7.0,66.0,1.0,...,Urola Kosta,Gipuzkoa,4322.0,1.0,1.0,943812880.0,566895.467319775,4779579.900333860,itur2000@gmail.com,2024
55465,L0555741,Translimp Contract Service,NaN,NaN,Sin local propiamente dicho,NaN,20,NaN,NaN,NaN,...,NaN,Madrid,8121.0,3.0,5.0,916789100.0,.,.,comercial@translimp-cs.com,2024

# 2. Exploration

In [5]:
# Explore the combined DataFrame
print(f"Shape: {df_combined.shape[0]:,} rows × {df_combined.shape[1]:,} columns\n")

# 1. Column names and data types
print("=" * 80)
print("COLUMNS AND DATA TYPES")
print("=" * 80)

column_info = pd.DataFrame({
    "column": df_combined.columns,
    "dtype": df_combined.dtypes.astype(str),
    "non_null": df_combined.notna().sum(),
    "missing": df_combined.isna().sum(),
    "missing_%": (df_combined.isna().mean() * 100).round(2),
    "unique": df_combined.nunique(dropna=True)
    })

print(column_info.to_string(index=False))

Shape: 349,635 rows × 67 columns

================================================================================
COLUMNS AND DATA TYPES
================================================================================
                                      column   dtype  non_null  missing  missing_%  unique
                   Código de establecimiento  object    349635        0       0.00  102899
             Denominación de establecimiento  object    349635        0       0.00   95418
                Dirección de establecimiento  object    348370     1265       0.36   86291
     Aproximación postal del establecimiento  object      1009   348626      99.71     407
Complemento de dirección del establecimiento  object     54775   294860      84.33   14891
                               Código postal float64    348496     1139       0.33     113
                                          TH   int64    349635        0       0.00       1
                                       Comar float64    348501     1134       0.32       7
                                         Mun float64    348501     1134       0.32      88
                                    Distrito float64    348145     1490       0.43       7
                                     Sección float64    348145     1490       0.43      36
                                     Entidad float64    348145     1490       0.43      17
                                      Barrio float64    275062    74573      21.33      18
                                       Calle float64    348145     1490       0.43    1585
                                      Bloque  object      4903   344732      98.60      19
                                      Número float64    348145     1490       0.43     461
                                         BIS  object     18065   331570      94.83      31
                                    Escalera  object      3604   346031      98.97      27
                                        Piso  object    346859     2776       0.79      32
                                        Mano  object    167746   181889      52.02      29
                                      Puerta  object    132413   217222      62.13     285
                                Barrio texto  object    275062    74573      21.33     204
                                   Entidad.1  object    348145     1490       0.43     341
                                   Municipio  object    349635        0       0.00      91
                                     Comarca  object    349635        0       0.00      16
                                        TH.1  object    349635        0       0.00       1
                                   CNAE09      int64    349635        0       0.00     562
                                 Título CNAE  object    349635        0       0.00     562
                                     EMPLEST   int64    349635        0       0.00      10
                                coordenada x  object    349635        0       0.00   42914
                                coordenada y  object    349635        0       0.00   44379
                             Teléfono1 estab float64    234122   115513      33.04   57669
          Correo electrónico establecimiento  object     88109   261526      74.80   24610
                           Código de empresa  object    349631        4       0.00  100941
                                Razón Social  object    349631        4       0.00  111141
                        Dirección de empresa  object    337033    12602       3.60   91124
           Aproximación postal de la empresa  object     13594   336041      96.11    3969
      Complemento de dirección de la empresa  object     47178   302457      86.51   11972
                                  CP empresa float64    349631        4       0.00    1134
                                        PROV float64    349631        4       0.00      49
                                       COMAR float64    337424    12211       3.49       7
                                       MUNIC float64    349631        4       0.00     236
                                         DIS float64    336821    12814       3.66       9
                                        SECC float64    336821    12814       3.66      46
                                     ENTIDAD float64    336821    12814       3.66      38
                                      BARRIO float64    265858    83777      23.96      66
                                       CALLE float64    336821    12814       3.66    1886
                                      BLOQUE  object      3766   345869      98.92      31
                                      NUMERO float64    336821    12814       3.66     455
                                       BIS.1  object     17548   332087      94.98      33
                                         ESC  object      4971   344664      98.58      36
                                        PISO  object    335662    13973       4.00      38
                                        MANO  object    195063   154572      44.21      32
                                      PUERTA  object     78545   271090      77.54     244
                                    BARRIO.1  object    265858    83777      23.96     386
                                   ENTIDAD.1  object    336821    12814       3.66     520
                                   MUNICIPIO  object    349631        4       0.00     731
                                     COMARCA  object    337424    12211       3.49      38
                                   PROVINCIA  object    349631        4       0.00      55
                                CNAE EMPRESA float64    349631        4       0.00     563
                                  NUM ESTABL float64    349631        4       0.00     123
                                     EMPLEMP float64    349631        4       0.00      10
                               Teléfono1 emp float64    232911   116724      33.38   55030
                            coordenada x emp  object    349631        4       0.00   44043
                            coordenada y emp  object    349631        4       0.00   45492
                  Correo electrónico empresa  object     94967   254668      72.84   23480
                                        Year   int64    349635        0       0.00       6

In [6]:
# 2. Numerical columns
numeric_cols = df_combined.select_dtypes(include=np.number).columns

print("\n" + "=" * 80)
print("NUMERICAL COLUMNS")
print("=" * 80)

if len(numeric_cols) > 0:
    numeric_summary = df_combined[numeric_cols].describe().T

    numeric_summary["missing"] = df_combined[numeric_cols].isna().sum()
    numeric_summary["missing_%"] = (
        df_combined[numeric_cols].isna().mean() * 100
    ).round(2)

    print(numeric_summary.to_string())
else:
    print("No numerical columns found.")

================================================================================
NUMERICAL COLUMNS
================================================================================
                    count          mean           std          min          25%          50%          75%          max  missing  missing_%
Código postal    348496.0  2.027320e+04  2.745970e+02      20001.0      20016.0      20180.0      20500.0      20950.0     1139       0.33
TH               349635.0  2.000000e+01  0.000000e+00         20.0         20.0         20.0         20.0         20.0        0       0.00
Comar            348501.0  3.986640e+00  1.615998e+00          1.0          4.0          4.0          5.0          7.0     1134       0.32
Mun              348501.0  8.775393e+01  1.635826e+02          1.0         45.0         69.0         69.0        907.0     1134       0.32
Distrito         348145.0  2.475052e+00  1.906688e+00          1.0          1.0          1.0          3.0          7.0     1490       0.43
Sección          348145.0  7.287613e+00  7.840528e+00          1.0          2.0          4.0          9.0         36.0     1490       0.43
Entidad          348145.0  3.633472e+00  2.153146e+00          1.0          2.0          4.0          5.0         17.0     1490       0.43
Barrio           275062.0  5.853749e+00  3.954598e+00          1.0          3.0          5.0          8.0         18.0    74573      21.33
Calle            348145.0  2.911528e+03  2.136131e+03          1.0       1220.0       2030.0       4310.0       9001.0     1490       0.43
Número           348145.0  2.082040e+01  3.937324e+01          0.0          4.0         10.0         24.0        999.0     1490       0.43
CNAE09           349635.0  5.748980e+03  2.220114e+03        111.0       4611.0       4941.0       7311.0       9609.0        0       0.00
EMPLEST          349635.0  1.607476e+00  1.312479e+00          1.0          1.0          1.0          2.0         10.0        0       0.00
Teléfono1 estab  234122.0  9.066629e+08  9.778616e+07  600000000.0  943212507.0  943441371.0  943652041.5  999780958.0   115513      33.04
CP empresa       349631.0  2.074977e+04  4.952934e+03       1001.0      20016.0      20180.0      20560.0      51004.0        4       0.00
PROV             349631.0  2.048292e+01  4.942455e+00          1.0         20.0         20.0         20.0         51.0        4       0.00
COMAR            337424.0  3.934252e+00  1.634988e+00          1.0          3.0          4.0          4.0          7.0    12211       3.49
MUNIC            349631.0  8.821497e+01  1.633518e+02          1.0         43.0         67.0         69.0        916.0        4       0.00
DIS              336821.0  2.570727e+00  1.967603e+00          1.0          1.0          2.0          4.0          9.0    12814       3.66
SECC             336821.0  7.692917e+00  8.078628e+00          1.0          2.0          4.0         10.0         46.0    12814       3.66
ENTIDAD          336821.0  4.415301e+00  9.816789e+00          1.0          2.0          4.0          5.0        603.0    12814       3.66
BARRIO           265858.0  1.328367e+01  6.440563e+01          1.0          3.0          5.0          9.0        805.0    83777      23.96
CALLE            336821.0  2.948899e+03  2.174141e+03          1.0       1230.0       2114.0       4450.0      16000.0    12814       3.66
NUMERO           336821.0  2.132056e+01  4.047515e+01          0.0          4.0         11.0         25.0        999.0    12814       3.66
CNAE EMPRESA     349631.0  5.739519e+03  2.227321e+03        111.0       4531.0       4941.0       7320.0       9700.0        4       0.00
NUM ESTABL       349631.0  1.127768e+01  8.561019e+01          1.0          1.0          1.0          1.0       1031.0        4       0.00
EMPLEMP          349631.0  2.055301e+00  2.097151e+00          1.0          1.0          1.0          2.0         10.0        4       0.00
Teléfono1 emp    232911.0  9.018994e+08  1.026025e+08  600014307.0  943160682.5  943433772.0  943674102.0  999780958.0   116724      33.38
Year             349635.0  2.018896e+03  3.410427e+00       2014.0       2016.0       2018.0       2022.0       2024.0        0       0.00

In [7]:
# 3. Categorical / object columns
categorical_cols = df_combined.select_dtypes(
    include=["object", "category", "bool"]
).columns

print("\n" + "=" * 80)
print("CATEGORICAL COLUMNS")
print("=" * 80)

if len(categorical_cols) > 0:
    for col in categorical_cols:
        print(f"\n--- {col} ---")
        print(f"Unique values: {df_combined[col].nunique(dropna=True)}")
        print(f"Missing values: {df_combined[col].isna().sum()}")

        print("\nTop values:")
        print(df_combined[col].value_counts(dropna=False).head(10).to_string())
else:
    print("No categorical columns found.")

================================================================================
CATEGORICAL COLUMNS
================================================================================

--- Código de establecimiento ---
Unique values: 102899
Missing values: 0

Top values:
Código de establecimiento
L0337314    9
L0089814    7
L0194246    6
L0193994    6
L0193995    6
L0194020    6
L0374557    6
L0374545    6
L0194130    6
L0194210    6

--- Denominación de establecimiento ---
Unique values: 95418
Missing values: 0

Top values:
Denominación de establecimiento
Transporte de mercancías                   3941
Construcción de edificios residenciales    2296
Asesoría                                   1909
Enseñanza                                  1904
Albañilería                                1726
Taxi                                       1666
Arquitectura                               1621
Abogacía                                   1575
Fontanería                                 1289
Instalaciones de carpintería               1234

--- Dirección de establecimiento ---
Unique values: 86291
Missing values: 1265

Top values:
Dirección de establecimiento
NaN                                    1265
PS Miramon, 174, Bajo, 1                367
PS Miramon, 174, Bajo, 4                163
CL Urbieta, 9, Bajo                     133
AV Gudarien, 29, Bajo                   123
CL Alkolea, 7, Bajo, 1                  116
NU Loiola Auzoa, 25, Esc. A, Bajo        95
CL Alfonso XI, 10, Bajo, Mano G, 6A      95
CL Estacion Renfe, S/N, Bajo, 1          88
CL Goiru, 7, Bajo                        86

--- Aproximación postal del establecimiento ---
Unique values: 407
Missing values: 348626

Top values:
Aproximación postal del establecimiento
NaN                           348626
Apartado de Correos 87            10
Apartado de Correos 10             8
Apartado de Correos 58             7
Apartado de Correos Nº 98          6
Apartado 48                        6
Apdo. de Correos 116               6
Apartado de Correos Nº 222         6
Apartado Correos, 294              6
Apartado Correo 604                6

--- Complemento de dirección del establecimiento ---
Unique values: 14891
Missing values: 294860

Top values:
Complemento de dirección del establecimiento
NaN                            294860
Sin local propiamente dicho      1135
Trasera                           365
Dentro de Caja Laboral            238
Centro Comercial Garbera          214
Centro Comercial Urbil            158
TRASERA                           121
BAJO                              112
BJ                                103
Centro Comercial Txingudi         102

--- Bloque ---
Unique values: 19
Missing values: 344732

Top values:
Bloque
NaN    344732
A        3629
B         237
H         208
C         128
I         104
E          91
G          84
F          66
L          59

--- BIS ---
Unique values: 31
Missing values: 331570

Top values:
BIS
NaN    331570
A        8207
B        4865
C        1501
Y         932
D         709
E         406
F         228
G         179
1         147

--- Escalera ---
Unique values: 27
Missing values: 346031

Top values:
Escalera
NaN    346031
DR        957
IZ        860
A         630
B         229
01        201
02        156
03        122
CN         99
EX         69

--- Piso ---
Unique values: 32
Missing values: 2776

Top values:
Piso
B      222914
01      37542
02      25957
03      20927
04      14564
05       8414
06       4883
E        3485
NaN      2776
07       2360

--- Mano ---
Unique values: 29
Missing values: 181889

Top values:
Mano
NaN    181889
DR      50018
IZ      39398
A       24444
B       20615
C       12722
D        9360
T        4166
E        1883
CN       1302

--- Puerta ---
Unique values: 285
Missing values: 217222

Top values:
Puerta
NaN    217222
001     84833
002     19690
003      6300
004      3549
005      2026
006      1544
007      1225
008       921
009       777

--- Barrio texto ---
Unique values: 204
Missing values: 74573

Top values:
Barrio texto
NaN              74573
Centro           41845
Casco Viejo      14594
Gros             13848
Amara Berri      13509
Ibaeta            9119
Antiguo           8399
Casco Antiguo     7895
Egia              7009
Altza             6318

--- Entidad.1 ---
Unique values: 341
Missing values: 1490

Top values:
Entidad.1
Donostia / San Sebastián    109268
Irun                         31434
Errenteria                   13677
Eibar                        11087
Zarautz                      10998
Arrasate/Mondragón            7552
Azpeitia                      6864
Hernani                       6339
Tolosa                        6179
Bergara                       5585

--- Municipio ---
Unique values: 91
Missing values: 0

Top values:
Municipio
Donostia / San Sebastián    111307
Irun                         31495
Errenteria                   13806
Eibar                        11186
Zarautz                      11176
Hernani                       9497
Tolosa                        9161
Azpeitia                      7503
Hondarribia                   7351
Oiartzun                      7310

--- Comarca ---
Unique values: 16
Missing values: 0

Top values:
Comarca
Donostialdea/Donostia-San Sebastián    89733
Donostialdea                           85889
Goierri                                28369
Bidasoa Beherea / Bajo Bidasoa         18784
Urola-Kostaldea/Urola Costa            18526
Urola Kosta                            17296
Bidasoa Beherea/Bajo Bidasoa           13453
Tolosaldea/Tolosa                      12059
Deba Garaia/Alto Deba                  12044
Debabarrena / Bajo Deba                11314

--- TH.1 ---
Unique values: 1
Missing values: 0

Top values:
TH.1
Gipuzkoa    349635

--- Título CNAE ---
Unique values: 562
Missing values: 0

Top values:
Título CNAE
Establecimientos de bebidas                                                      13614
Transporte de mercancías por carretera                                           12179
Peluquería y otros tratamientos de belleza                                       11479
Otras actividades sanitarias                                                      9241
Restaurantes y puestos de comidas                                                 9056
Construcción de edificios residenciales                                           8983
Actividades jurídicas                                                             8640
Otra educación n.c.o.p.                                                           7862
Comercio al por menor de prendas de vestir en establecimientos especializados     7410
Servicios técnicos de arquitectura                                                6829

---   coordenada x ---
Unique values: 42914
Missing values: 0

Top values:
  coordenada x
.                   1507
582671.795935815     590
590586.511862469     558
585527.232865406     379
579162.686191344     339
590591.451123202     326
579257.026895935     322
582679.118245550     320
580629.102403421     269
583223.203789737     264

---   coordenada y ---
Unique values: 44379
Missing values: 0

Top values:
  coordenada y
.                    1507
4793514.653955060     590
4794955.780617900     558
4795637.261904350     379
4791873.318044240     339
4794852.671605440     326
4794760.680330000     322
4796860.472923290     320
4796010.645903120     269
4795230.284743380     264

--- Correo electrónico establecimiento ---
Unique values: 24610
Missing values: 261526

Top values:
Correo electrónico establecimiento
NaN                                    261526
jdiezgon@kutxabank.es                     381
maria_jesus_turienzo@eroski.es            227
miren.etxarri@laboralkutxa.com            176
smorante@caixabank.com                    175
agurtzane.azcarate@laboralkutxa.com       146
aansobor@sabadellguipuzcoano.com          142
eduardo.alba@correos.com                  112
cristina.lopez.castelo@diagroup.com       102
tgeulate@uvesco.com                        86

--- Código de empresa ---
Unique values: 100941
Missing values: 4

Top values:
Código de empresa
J0001939    2266
J0016981     673
J0333477     651
J0189867     537
J0346319     423
J0143099     361
J0020644     335
J0355381     312
J0016624     291
J0348625     277

--- Razón Social ---
Unique values: 111141
Missing values: 4

Top values:
Razón Social
Eusko Jaurlaritza - Gobierno Vasco                   2266
Kutxabank S.A.                                        651
Consorcio Haurreskolak                                537
Ente Público Osakidetza - Servicio Vasco de Salud     473
Sociedad Estatal Correos y Telégrafos S.A.            361
Caja Laboral Bancaseguros S.L.U.                      312
Caja Laboral S.Coop. de Crédito                       296
Eroski S.Coop.                                        283
CaixaBank S.A.                                        277
Banco Bilbao Vizcaya Argentaria S.A.                  260

--- Dirección de empresa ---
Unique values: 91124
Missing values: 12602

Top values:
Dirección de empresa
NaN                                              12602
CL Donostia-San Sebastián, 1, Bajo, 1             2284
CL Gran Vía Don Diego López de Haro, 30, Bajo      653
BA San Agustín, 3, Bajo, 1                         464
CL Alava, 45, Bajo, 2                              437
PS Jose M. Arizmendiarrieta, 4, Bajo               434
AV Otaola, 29, Bajo, 1                             366
CL Gran Vía Don Diego López de Haro, 2, Bajo       312
PL Gipuzkoa, 1, Bajo                               310
CM Illarra, 4, Bajo, 2                             240

--- Aproximación postal de la empresa ---
Unique values: 3969
Missing values: 336041

Top values:
Aproximación postal de la empresa
NaN                          336041
CL Via Dublín, 7                361
AV Diagonal, 621-629            236
Ps. De Pereda, 9-12             231
PL Fueros, 1, Bajo              147
Oscar Esplá, 37                 110
CL Vía de los Poblados, 1        92
AV Llano Castellano, 51          86
CL Jacinto Benavente, 2-A        75
CL Velázquez, 34                 72

--- Complemento de dirección de la empresa ---
Unique values: 11972
Missing values: 302457

Top values:
Complemento de dirección de la empresa
NaN                                                   302457
Edificio Jaizkibel 1                                     537
Campo de las Naciones                                    363
Edificio Blanca Vinuesa                                  198
Dentro de Caja Laboral                                   196
Trasera                                                  195
Polígono Industi Bidaurre-Ureder. Edificio Unialco       176
Goienetxe                                                140
Polígono 108 - Grupo Ogi Berri                           110
POLIGONO 27                                               97

--- BLOQUE ---
Unique values: 31
Missing values: 345869

Top values:
BLOQUE
NaN    345869
A        2462
B         234
H         180
C         110
P         103
G          94
I          87
E          74
L          62

--- BIS.1 ---
Unique values: 33
Missing values: 332087

Top values:
BIS.1
NaN    332087
A        7318
B        5037
C        1458
Y         919
D         711
E         443
F         311
G         217
K         167

--- ESC ---
Unique values: 36
Missing values: 344664

Top values:
ESC
NaN    344664
DR       1358
IZ       1278
A         704
01        352
B         307
02        263
03        141
CN        116
04        115

--- PISO ---
Unique values: 38
Missing values: 13973

Top values:
PISO
B      154481
01      48566
02      39588
03      32948
04      23940
05      14024
NaN     13973
06       7871
07       3735
E        2623

--- MANO ---
Unique values: 32
Missing values: 154572

Top values:
MANO
NaN    154572
DR      44462
IZ      37873
A       35792
B       31516
C       20329
D       14407
E        2859
T        2018
CN       1793

--- PUERTA ---
Unique values: 244
Missing values: 271090

Top values:
PUERTA
NaN    271090
001     48150
002     10534
003      3735
004      2188
005      1341
006      1087
007      1038
008       721
009       613

--- BARRIO.1 ---
Unique values: 386
Missing values: 83777

Top values:
BARRIO.1
NaN            83777
Centro         32296
Amara Berri    12930
Casco Viejo    11966
Gros           11298
Ibaeta          9042
Antiguo         7961
Altza           6736
Aiete           6528
Egia            6282

--- ENTIDAD.1 ---
Unique values: 520
Missing values: 12814

Top values:
ENTIDAD.1
Donostia / San Sebastián    101260
Irun                         29304
Errenteria                   12968
NaN                          12814
Zarautz                      10644
Eibar                         9903
Arrasate/Mondragón            7116
Azpeitia                      6388
Hernani                       6054
Tolosa                        5039

--- MUNICIPIO ---
Unique values: 731
Missing values: 4

Top values:
MUNICIPIO
Donostia / San Sebastián    103432
Irun                         29377
Errenteria                   13102
Zarautz                      10820
Eibar                        10024
Hernani                       9107
Tolosa                        7998
Hondarribia                   7856
Azpeitia                      7098
Oiartzun                      6782

--- COMARCA ---
Unique values: 38
Missing values: 12211

Top values:
COMARCA
Donostialdea/Donostia-San Sebastián    84362
Donostialdea                           80116
Goierri                                26087
Bidasoa Beherea / Bajo Bidasoa         18049
Urola-Kostaldea/Urola Costa            17786
Urola Kosta                            16582
Bidasoa Beherea/Bajo Bidasoa           12837
NaN                                    12211
Tolosaldea/Tolosa                      11340
Deba Garaia/Alto Deba                  11189

--- PROVINCIA ---
Unique values: 55
Missing values: 4

Top values:
PROVINCIA
Gipuzkoa             326533
Bizkaia                6796
Madrid                 5460
Araba/Álava            4093
Barcelona              2503
Navarra                1318
Cantabria               412
Zaragoza                253
Valencia/València       240
Alicante/Alacant        183

---   coordenada x emp ---
Unique values: 44043
Missing values: 4

Top values:
  coordenada x emp
.                   12826
525544.537177715     2284
505487.881491883      653
526242.803518549      555
541694.097444128      537
590586.511862469      469
540850.291951469      434
536033.350072423      378
579542.184683381      345
582486.511814483      310

---   coordenada y emp ---
Unique values: 45492
Missing values: 4

Top values:
  coordenada y emp
.                    12826
4745187.980709640     2284
4789979.743475870      653
4742792.308341820      555
4780948.611736620      537
4794955.780617900      469
4775421.906681450      464
4767534.762086920      434
4795334.513527910      345
4796955.683543440      310

--- Correo electrónico empresa ---
Unique values: 23480
Missing values: 254668

Top values:
Correo electrónico empresa
NaN                                    254668
hezkuntza@hezkuntza.net                  1123
haurreskolak@haurreskolak.eus             452
solicitudes@kutxabank.es                  374
coordinacion@osakidetza.eus               355
adiezy@gruposantander.com                 231
agurtzane.azcarate@laboralkutxa.com       203
gipuzkoa@gipuzkoa.eus                     198
jdiezgon@kutxabank.es                     198
miren.etxarri@laboralkutxa.com            194

In [8]:
# 4. Duplicates

print("\n" + "=" * 80)
print("DUPLICATES")
print("=" * 80)

duplicate_count = df_combined.duplicated().sum()
duplicate_pct = duplicate_count / len(df_combined) * 100

print(f"Duplicate rows: {duplicate_count:,} ({duplicate_pct:.2f}%)")

================================================================================
DUPLICATES
================================================================================
Duplicate rows: 0 (0.00%)

# 3. Preprocessing

In [9]:
# Identify rows without valid coordinates
df_combined[~pd.to_numeric(df_combined['  coordenada x'], errors = 'coerce').notna() | ~pd.to_numeric(df_combined['  coordenada y'], errors = 'coerce').notna()]

,Código de establecimiento,Denominación de establecimiento,Dirección de establecimiento,Aproximación postal del establecimiento,Complemento de dirección del establecimiento,Código postal,TH,Comar,Mun,Distrito,...,COMARCA,PROVINCIA,CNAE EMPRESA,NUM ESTABL,EMPLEMP,Teléfono1 emp,coordenada x emp,coordenada y emp,Correo electrónico empresa,Year
272,L0001819,BAR RESTAURANTE TEDONE,"CL Corta 13, Piso: B",NaN,NaN,20001.0,20,4.0,69.0,NaN,...,Donostialdea/Donostia-San Sebastián,Gipuzkoa,5610.0,1.0,1.0,943273561.0,.,.,NaN,2014
2827,L0020105,Parque Zapatari de La Diputación Foral de Gipu...,"PL Zapatari, S/N",NaN,NaN,20009.0,20,4.0,69.0,6.0,...,Donostialdea/Donostia-San Sebastián,Gipuzkoa,8411.0,47.0,10.0,943482111.0,582486.511814483,4796955.683543440,NaN,2014
3047,L0021015,CONSULTORIO DE EGIA,"CL Tejería, 3",NaN,NaN,20012.0,20,4.0,69.0,4.0,...,Arabako Lautada/Llanada Alavesa,Araba/Álava,8610.0,348.0,10.0,945006555.0,526242.803518549,4742792.308341820,NaN,2014
3354,L0022377,Club Deportivo Vasconia,NaN,"CL Arroka, 6, 1º, Mano DR -",NaN,20006.0,20,4.0,69.0,NaN,...,Donostialdea/Donostia-San Sebastián,Gipuzkoa,8551.0,1.0,2.0,943466745.0,.,.,NaN,2014
3374,L0022525,Ferrovial Agroman,NaN,NaN,Sin local propiamente dicho,NaN,20,NaN,NaN,NaN,...,NaN,Madrid,4122.0,3.0,7.0,913008500.0,.,.,ferrovial@ferrovial.es,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55017,L0553404,Taxi,NaN,NaN,Sin local propiamente dicho,NaN,20,NaN,NaN,NaN,...,NaN,Navarra,4932.0,1.0,1.0,606824359.0,.,.,Paula.Puente1@gmail.com,2024
55287,L0554570,Cocina Central Goñi,NaN,NaN,Sin local propiamente dicho,NaN,20,NaN,NaN,NaN,...,Bilbo Handia / Gran Bilbao,Bizkaia,5629.0,3.0,9.0,944630588.0,500904.437185768,4795878.002902220,ausolan@ausolan.com,2024
55293,L0554597,Solpriga,NaN,NaN,Sin local propiamente dicho,NaN,20,NaN,NaN,NaN,...,NaN,Jaén,4110.0,2.0,3.0,688690992.0,.,.,info@solpriga.com,2024
55359,L0555033,Viatek Seguridad,NaN,NaN,Sin local propiamente dicho,NaN,20,NaN,NaN,NaN,...,NaN,Madrid,4321.0,2.0,3.0,NaN,.,.,eloisa.lopez@grupoviatek.com,2024
55465,L0555741,Translimp Contract Service,NaN,NaN,Sin local propiamente dicho,NaN,20,NaN,NaN,NaN,...,NaN,Madrid,8121.0,3.0,5.0,916789100.0,.,.,comercial@translimp-cs.com,2024

In [10]:
# Select the columns of interest
id_vars = ['Código de establecimiento', 'Denominación de establecimiento', 'Municipio', 'CNAE09   ', 'EMPLEST', '  coordenada x', '  coordenada y', 'Year']
value_vars = [col for col in df_combined.columns if col in id_vars]
df_combined_filtered = df_combined[value_vars]
df_combined_filtered = df_combined_filtered.rename(columns = {'Código de establecimiento': 'ID', 'Denominación de establecimiento': 'Name', 'Municipio': 'Municipality', 'CNAE09   ': 'CNAE', 'EMPLEST': 'EMPLEST', '  coordenada x': 'x', '  coordenada y': 'y'})
df_combined_filtered

,ID,Name,Municipality,CNAE,EMPLEST,x,y,Year
0,L0000074,CAF,Beasain,3020,10,566017.911586412,4766769.637825750,2014
1,L0000075,CAF,Irun,3020,9,596812.041847544,4799327.760714000,2014
2,L0000084,Goenaga,Zaldibia,4672,2,569178.939505614,4765813.062533880,2014
3,L0000090,Aquarbe,Zumarraga,3600,2,555801.318749450,4771035.809458850,2014
4,L0000105,Ayestaran Ferreteria,Donostia / San Sebastián,4674,2,583245.088260498,4796927.229335210,2014
...,...,...,...,...,...,...,...,...
55461,L0555725,Norbide,Donostia / San Sebastián,8299,2,582001.821086761,4795791.210568550,2024
55462,L0555726,Limpiezas Soldene,Donostia / San Sebastián,8121,6,580440.289060730,4795634.772411080,2024
55463,L0555727,Asoc. Benefica Asistencial Elkarbanatuz,Irun,9499,3,597331.818642745,4798751.108089970,2024
55464,L0555731,Fontanería,Errezil,4322,1,566895.467319775,4779579.900333860,2024
55465,L0555741,Translimp Contract Service,No determinado de Gipuzkoa,8121,2,.,.,2024

In [11]:
# Drop rows with missing values in critical columns
df_combined_filtered = df_combined_filtered[pd.to_numeric(df_combined_filtered['x'], errors = 'coerce').notna() & pd.to_numeric(df_combined_filtered['y'], errors = 'coerce').notna()]
df_combined_filtered

,ID,Name,Municipality,CNAE,EMPLEST,x,y,Year
0,L0000074,CAF,Beasain,3020,10,566017.911586412,4766769.637825750,2014
1,L0000075,CAF,Irun,3020,9,596812.041847544,4799327.760714000,2014
2,L0000084,Goenaga,Zaldibia,4672,2,569178.939505614,4765813.062533880,2014
3,L0000090,Aquarbe,Zumarraga,3600,2,555801.318749450,4771035.809458850,2014
4,L0000105,Ayestaran Ferreteria,Donostia / San Sebastián,4674,2,583245.088260498,4796927.229335210,2014
...,...,...,...,...,...,...,...,...
55460,L0555718,Aloe Loredenda,Urnieta,4776,1,581859.769927073,4789023.088200280,2024
55461,L0555725,Norbide,Donostia / San Sebastián,8299,2,582001.821086761,4795791.210568550,2024
55462,L0555726,Limpiezas Soldene,Donostia / San Sebastián,8121,6,580440.289060730,4795634.772411080,2024
55463,L0555727,Asoc. Benefica Asistencial Elkarbanatuz,Irun,9499,3,597331.818642745,4798751.108089970,2024
55464,L0555731,Fontanería,Errezil,4322,1,566895.467319775,4779579.900333860,2024

In [12]:
# Change municipality names for consistency
df_combined_filtered['Municipality'] = df_combined_filtered['Municipality'].replace({'Arrasate / Mondragón': 'Arrasate/Mondragón', 'Leintz Gatzaga': 'Leintz-Gatzaga'})

C:\Users\narronizari\AppData\Local\Temp\ipykernel_25776\1598790180.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_combined_filtered['Municipality'] = df_combined_filtered['Municipality'].replace({'Arrasate / Mondragón': 'Arrasate/Mondragón', 'Leintz Gatzaga': 'Leintz-Gatzaga'})

# Processing

In [13]:
# ── CNAE classification — González-Feliu et al. (2020) ───────────────────────
_CNAE_RANGES = [
    (111,   322,   "Agriculture"),
    (510,   990,   "Primary and intermediate products"),
    (1011,  1820,  "Primary and intermediate products"),
    (2311,  3320,  "Primary and intermediate products"),
    (3512,  3530,  "Primary and intermediate products"),
    (3600,  3900,  "Primary and intermediate products"),
    (1910,  2229,  "Chemical industry"),
    (4110,  4399,  "Construction industry"),
    (4611,  4690,  "Wholesale"),
    (4711,  4711,  "Food and non-fragile consumer goods"),
    (4721,  4721,  "Food and non-fragile consumer goods"),
    (4723,  4723,  "Food and non-fragile consumer goods"),
    (4725,  4729,  "Food and non-fragile consumer goods"),
    (4776,  4776,  "Food and non-fragile consumer goods"),
    (4722,  4722,  "Butcher's shops"),
    (4724,  4724,  "Bakery retailers"),
    (4741,  4743,  "Hardware stores"),
    (4751,  4759,  "Furnishing shops"),
    (4761,  4765,  "Bookshops"),
    (4771,  4772,  "Clothing, shoes, leather"),
    (4719,  4719,  "Other retail shops"),
    (4730,  4730,  "Other retail shops"),
    (4774,  4775,  "Other retail shops"),
    (4777,  4779,  "Other retail shops"),
    (4791,  4799,  "Other retail shops"),
    (4773,  4773,  "Pharmacies"),
    (4781,  4789,  "Street trading (marketplaces)"),
    (4910,  5122,  "Only Transport"),
    (5210,  5320,  "Transport and warehousing"),
    (5510,  5630,  "Hotels, restaurants, cafés"),
    (4511,  4540,  "Tertiary (non-offices) and services"),
    (5811,  6399,  "Tertiary (non-offices) and services"),
    (6411,  6630,  "Tertiary (non-offices) and services"),
    (6810,  6832,  "Tertiary (non-offices) and services"),
    (8510,  8560,  "Tertiary (non-offices) and services"),
    (8610,  8899,  "Tertiary (non-offices) and services"),
    (9602,  9602,  "Tertiary (non-offices) and services"),
    (6910,  7500,  "Offices"),
    (7711,  8299,  "Offices"),
    (8411,  8430,  "Offices"),
    (9411,  9601,  "Offices"),
    (9603,  9609,  "Offices"),
    (9001,  9329,  "Craftsmen"),
    (9700,  9820,  "Other"),
    (9900,  9900,  "Other"),
]
_GROUP_MAP = {
    "Agriculture":                          "Agriculture",
    "Primary and intermediate products":    "Primary and intermediate products",
    "Chemical industry":                    "Chemical industry",
    "Construction industry":                "Construction industry",
    "Wholesale":                            "Wholesale",
    "Food and non-fragile consumer goods":  "Food and non-fragile retail",
    "Butcher's shops":                      "Food and basic goods retail",
    "Bakery retailers":                     "Food and basic goods retail",
    "Hardware stores":                      "Specialized retail",
    "Furnishing shops":                     "Specialized retail",
    "Bookshops":                            "Specialized retail",
    "Clothing, shoes, leather":             "Specialized retail",
    "Other retail shops":                   "Specialized retail",
    "Pharmacies":                           "Pharmacies",
    "Street trading (marketplaces)":        "Street trading",
    "Only Transport":                       "Transport and warehousing",
    "Transport and warehousing":            "Transport and warehousing",
    "Hotels, restaurants, cafés":           "Hotels, restaurants, cafés",
    "Tertiary (non-offices) and services":  "Tertiary (non-offices) and services",
    "Offices":                              "Offices",
    "Craftsmen":                            "Craftsmen",
    "Other":                                "Other",
}

# EMPLEST ordinal code → employee count range
_EMP_RANGE = {1:    (1, 2),
              2:    (3, 5),
              3:    (6, 9),
              4:    (10, 14),
              5:    (15, 19),
              6:    (20, 49),
              7:    (50, 99),
              8:    (100, 249),
              9:    (250, 499),
              10:   (500, 500)}

In [14]:
# Classify CNAE
cnae_ranges = pd.DataFrame(
    _CNAE_RANGES, columns=["min_CNAE", "max_CNAE", "sector"]
    )
conditions = [
        (df_combined_filtered["CNAE"] >= r.min_CNAE) & (df_combined_filtered["CNAE"] <= r.max_CNAE)
        for r in cnae_ranges.itertuples()
    ]
df_combined_filtered.loc[:, "sector"] = np.select(conditions, cnae_ranges["sector"].values, default=None)
df_combined_filtered.loc[:, "group"]  = df_combined_filtered["sector"].map(_GROUP_MAP)
df_combined_filtered

C:\Users\narronizari\AppData\Local\Temp\ipykernel_25776\2520199904.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_combined_filtered.loc[:, "sector"] = np.select(conditions, cnae_ranges["sector"].values, default=None)
C:\Users\narronizari\AppData\Local\Temp\ipykernel_25776\2520199904.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_combined_filtered.loc[:, "group"]  = df_combined_filtered["sector"].map(_GROUP_MAP)

,ID,Name,Municipality,CNAE,EMPLEST,x,y,Year,sector,group
0,L0000074,CAF,Beasain,3020,10,566017.911586412,4766769.637825750,2014,Primary and intermediate products,Primary and intermediate products
1,L0000075,CAF,Irun,3020,9,596812.041847544,4799327.760714000,2014,Primary and intermediate products,Primary and intermediate products
2,L0000084,Goenaga,Zaldibia,4672,2,569178.939505614,4765813.062533880,2014,Wholesale,Wholesale
3,L0000090,Aquarbe,Zumarraga,3600,2,555801.318749450,4771035.809458850,2014,Primary and intermediate products,Primary and intermediate products
4,L0000105,Ayestaran Ferreteria,Donostia / San Sebastián,4674,2,583245.088260498,4796927.229335210,2014,Wholesale,Wholesale
...,...,...,...,...,...,...,...,...,...,...
55460,L0555718,Aloe Loredenda,Urnieta,4776,1,581859.769927073,4789023.088200280,2024,Food and non-fragile consumer goods,Food and non-fragile retail
55461,L0555725,Norbide,Donostia / San Sebastián,8299,2,582001.821086761,4795791.210568550,2024,Offices,Offices
55462,L0555726,Limpiezas Soldene,Donostia / San Sebastián,8121,6,580440.289060730,4795634.772411080,2024,Offices,Offices
55463,L0555727,Asoc. Benefica Asistencial Elkarbanatuz,Irun,9499,3,597331.818642745,4798751.108089970,2024,Offices,Offices
55464,L0555731,Fontanería,Errezil,4322,1,566895.467319775,4779579.900333860,2024,Construction industry,Construction industry

In [15]:
# Assign max number of employees
df_combined_filtered.loc[:, "Employees"] = df_combined_filtered["EMPLEST"].map(
    {k: v[1] for k, v in _EMP_RANGE.items()}
)
df_combined_filtered

C:\Users\narronizari\AppData\Local\Temp\ipykernel_25776\919119454.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_combined_filtered.loc[:, "Employees"] = df_combined_filtered["EMPLEST"].map(

,ID,Name,Municipality,CNAE,EMPLEST,x,y,Year,sector,group,Employees
0,L0000074,CAF,Beasain,3020,10,566017.911586412,4766769.637825750,2014,Primary and intermediate products,Primary and intermediate products,500
1,L0000075,CAF,Irun,3020,9,596812.041847544,4799327.760714000,2014,Primary and intermediate products,Primary and intermediate products,499
2,L0000084,Goenaga,Zaldibia,4672,2,569178.939505614,4765813.062533880,2014,Wholesale,Wholesale,5
3,L0000090,Aquarbe,Zumarraga,3600,2,555801.318749450,4771035.809458850,2014,Primary and intermediate products,Primary and intermediate products,5
4,L0000105,Ayestaran Ferreteria,Donostia / San Sebastián,4674,2,583245.088260498,4796927.229335210,2014,Wholesale,Wholesale,5
...,...,...,...,...,...,...,...,...,...,...,...
55460,L0555718,Aloe Loredenda,Urnieta,4776,1,581859.769927073,4789023.088200280,2024,Food and non-fragile consumer goods,Food and non-fragile retail,2
55461,L0555725,Norbide,Donostia / San Sebastián,8299,2,582001.821086761,4795791.210568550,2024,Offices,Offices,5
55462,L0555726,Limpiezas Soldene,Donostia / San Sebastián,8121,6,580440.289060730,4795634.772411080,2024,Offices,Offices,49
55463,L0555727,Asoc. Benefica Asistencial Elkarbanatuz,Irun,9499,3,597331.818642745,4798751.108089970,2024,Offices,Offices,9
55464,L0555731,Fontanería,Errezil,4322,1,566895.467319775,4779579.900333860,2024,Construction industry,Construction industry,2

In [16]:
df_combined_filtered.to_csv('data/processed/establishments.csv', index=False, sep=',', decimal='.', encoding='utf-8')

In [17]:
# Convert to geospatial data
gpd.GeoDataFrame(
    df_combined_filtered,
    geometry=gpd.points_from_xy(df_combined_filtered["x"], df_combined_filtered["y"]),
    crs='EPSG:25830' # UTM zone 30N — good for Gipuzkoa
    ).to_file('data/processed/establishments.geojson', driver='GeoJSON')

# 4. Analysis

In [18]:
from utils.summaries import analyse_trends, grouped_summary

## Tag employees and CNAE groups

## BY MUNICIPALITY

In [19]:
df_combined_filtered.loc[:, 'Establishments'] = 1

C:\Users\narronizari\AppData\Local\Temp\ipykernel_25776\3483976035.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_combined_filtered.loc[:, 'Establishments'] = 1

In [20]:
analyse_trends(
    df_combined_filtered,
    category="Municipality",
    variables=["Employees"],
    sort_by="Employees"
)

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  DONOSTIA / SAN SEBASTIÁN
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                    18,740 (31.0%)                18,954 (31.8%)                18,769 (31.9%)                18,504 (32.3%)                18,353 (32.4%)                17,929 (32.4%)
  Growth                                              —                       🟢↑ 1.1%                       🔴↓ 1.0%                       🔴↓ 1.4%                       🔴↓ 0.8%                       🔴↓ 2.3%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                              120634.0 (30.6%)              124998.0 (31.2%)              128583.0 (31.2%)              133616.0 (31.3%)              131466.0 (31.0%)              139563.0 (31.9%)
  Mean ± SD                                  6.4 ± 25.9                    6.6 ± 26.8                    6.9 ± 26.6                    7.2 ± 28.2                    7.2 ± 28.0                    7.8 ± 30.5
  Q5–Q95                                       2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–19.0                      2.0–19.0                      2.0–19.0
  Growth                                              —                       🟢↑ 3.6%                       🟢↑ 2.9%                       🟢↑ 3.9%                       🔴↓ 1.6%                       🟢↑ 6.2%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  IRUN
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      5,581 (9.2%)                  5,386 (9.0%)                  5,388 (9.1%)                  5,136 (9.0%)                  5,092 (9.0%)                  4,904 (8.9%)
  Growth                                              —                       🔴↓ 3.5%                       🟢↑ 0.0%                       🔴↓ 4.7%                       🔴↓ 0.9%                       🔴↓ 3.7%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                30311.0 (7.7%)                30224.0 (7.5%)                32330.0 (7.8%)                32775.0 (7.7%)                31829.0 (7.5%)                32236.0 (7.4%)
  Mean ± SD                                  5.4 ± 19.1                    5.6 ± 19.5                    6.0 ± 22.0                    6.4 ± 22.7                    6.3 ± 21.6                    6.6 ± 22.4
  Q5–Q95                                       2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–19.0
  Growth                                              —                       🔴↓ 0.3%                       🟢↑ 7.0%                       🟢↑ 1.4%                       🔴↓ 2.9%                       🟢↑ 1.3%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  ARRASATE/MONDRAGÓN
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      1,378 (2.3%)                  1,345 (2.3%)                  1,325 (2.2%)                  1,289 (2.2%)                  1,284 (2.3%)                  1,251 (2.3%)
  Growth                                              —                       🔴↓ 2.4%                       🔴↓ 1.5%                       🔴↓ 2.7%                       🔴↓ 0.4%                       🔴↓ 2.6%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                15607.0 (4.0%)                15677.0 (3.9%)                16177.0 (3.9%)                16312.0 (3.8%)                16413.0 (3.9%)                16966.0 (3.9%)
  Mean ± SD                                 11.3 ± 49.7                   11.7 ± 48.8                   12.2 ± 49.7                   12.7 ± 50.9                   12.8 ± 52.0                   13.6 ± 54.6
  Q5–Q95                                       2.0–49.0                      2.0–49.0                      2.0–49.0                      2.0–49.0                      2.0–49.0                      2.0–49.0
  Growth                                              —                       🟢↑ 0.4%                       🟢↑ 3.2%                       🟢↑ 0.8%                       🟢↑ 0.6%                       🟢↑ 3.4%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  HERNANI
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      1,613 (2.7%)                  1,598 (2.7%)                  1,600 (2.7%)                  1,570 (2.7%)                  1,577 (2.8%)                  1,531 (2.8%)
  Growth                                              —                       🔴↓ 0.9%                       🟢↑ 0.1%                       🔴↓ 1.9%                       🟢↑ 0.4%                       🔴↓ 2.9%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                11693.0 (3.0%)                12129.0 (3.0%)                12511.0 (3.0%)                13596.0 (3.2%)                14016.0 (3.3%)                14738.0 (3.4%)
  Mean ± SD                                  7.2 ± 28.4                    7.6 ± 27.8                    7.8 ± 27.9                    8.7 ± 29.7                    8.9 ± 30.7                    9.6 ± 32.0
  Q5–Q95                                       2.0–19.0                      2.0–19.0                      2.0–19.0                      2.0–49.0                      2.0–49.0                      2.0–49.0
  Growth                                              —                       🟢↑ 3.7%                       🟢↑ 3.1%                       🟢↑ 8.7%                       🟢↑ 3.1%                       🟢↑ 5.2%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  ERRENTERIA
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      2,420 (4.0%)                  2,414 (4.1%)                  2,367 (4.0%)                  2,241 (3.9%)                  2,207 (3.9%)                  2,151 (3.9%)
  Growth                                              —                       🔴↓ 0.2%                       🔴↓ 1.9%                       🔴↓ 5.3%                       🔴↓ 1.5%                       🔴↓ 2.5%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                12549.0 (3.2%)                12725.0 (3.2%)                12638.0 (3.1%)                12398.0 (2.9%)                13255.0 (3.1%)                13457.0 (3.1%)
  Mean ± SD                                  5.2 ± 19.2                    5.3 ± 19.4                    5.3 ± 17.1                    5.5 ± 16.8                    6.0 ± 19.6                    6.3 ± 20.4
  Q5–Q95                                        2.0–9.0                       2.0–9.0                      2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–14.0
  Growth                                              —                       🟢↑ 1.4%                       🔴↓ 0.7%                       🔴↓ 1.9%                       🟢↑ 6.9%                       🟢↑ 1.5%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  EIBAR
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      1,945 (3.2%)                  1,914 (3.2%)                  1,899 (3.2%)                  1,864 (3.2%)                  1,827 (3.2%)                  1,737 (3.1%)
  Growth                                              —                       🔴↓ 1.6%                       🔴↓ 0.8%                       🔴↓ 1.8%                       🔴↓ 2.0%                       🔴↓ 4.9%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                12516.0 (3.2%)                12339.0 (3.1%)                12332.0 (3.0%)                13101.0 (3.1%)                13062.0 (3.1%)                12756.0 (2.9%)
  Mean ± SD                                  6.4 ± 23.7                    6.4 ± 21.0                    6.5 ± 21.0                    7.0 ± 23.3                    7.1 ± 25.5                    7.3 ± 23.8
  Q5–Q95                                       2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–19.0                      2.0–19.0                      2.0–19.0
  Growth                                              —                       🔴↓ 1.4%                       🔴↓ 0.1%                       🟢↑ 6.2%                       🔴↓ 0.3%                       🔴↓ 2.3%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  OIARTZUN
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      1,279 (2.1%)                  1,253 (2.1%)                  1,231 (2.1%)                  1,208 (2.1%)                  1,198 (2.1%)                  1,130 (2.0%)
  Growth                                              —                       🔴↓ 2.0%                       🔴↓ 1.8%                       🔴↓ 1.9%                       🔴↓ 0.8%                       🔴↓ 5.7%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                10526.0 (2.7%)                11222.0 (2.8%)                11282.0 (2.7%)                12549.0 (2.9%)                11896.0 (2.8%)                12230.0 (2.8%)
  Mean ± SD                                  8.2 ± 29.8                    9.0 ± 31.9                    9.2 ± 29.0                   10.4 ± 35.5                    9.9 ± 32.1                   10.8 ± 36.4
  Q5–Q95                                       2.0–19.0                      2.0–19.0                      2.0–49.0                      2.0–49.0                      2.0–49.0                      2.0–49.0
  Growth                                              —                       🟢↑ 6.6%                       🟢↑ 0.5%                      🟢↑ 11.2%                       🔴↓ 5.2%                       🟢↑ 2.8%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  ZARAUTZ
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      1,962 (3.2%)                  1,924 (3.2%)                  1,903 (3.2%)                  1,832 (3.2%)                  1,766 (3.1%)                  1,781 (3.2%)
  Growth                                              —                       🔴↓ 1.9%                       🔴↓ 1.1%                       🔴↓ 3.7%                       🔴↓ 3.6%                       🟢↑ 0.8%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                 9887.0 (2.5%)                10033.0 (2.5%)                10331.0 (2.5%)                10084.0 (2.4%)                10412.0 (2.5%)                10908.0 (2.5%)
  Mean ± SD                                  5.0 ± 18.9                    5.2 ± 19.3                    5.4 ± 20.1                    5.5 ± 20.4                    5.9 ± 22.8                    6.1 ± 23.0
  Q5–Q95                                        2.0–9.0                      2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–14.0
  Growth                                              —                       🟢↑ 1.5%                       🟢↑ 3.0%                       🔴↓ 2.4%                       🟢↑ 3.3%                       🟢↑ 4.8%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════


In [21]:
grouped_summary(
    df_combined_filtered[df_combined_filtered["Year"] == 2024],
    group_col="Municipality",
    variables=["Employees"],
    sort_by='Count'
)

,Count (%),Employees (%),Mean Employees per establishment ± SD (q5–q95)
Municipality,,,
Donostia / San Sebastián,"17,929 (32.4%)","139,563 (31.9%)",8 ± 30 (2–19)
Irun,"4,904 (8.9%)","32,236 (7.4%)",7 ± 22 (2–19)
Errenteria,"2,151 (3.9%)","13,457 (3.1%)",6 ± 20 (2–14)
Zarautz,"1,781 (3.2%)","10,908 (2.5%)",6 ± 23 (2–14)
Eibar,"1,737 (3.1%)","12,756 (2.9%)",7 ± 24 (2–19)
...,...,...,...
Orexa,14 (0.0%),44 (0.0%),3 ± 2 (2–6)
Gaztelu,13 (0.0%),32 (0.0%),2 ± 1 (2–5)
Leintz-Gatzaga,12 (0.0%),40 (0.0%),3 ± 2 (2–7)
Gaintza,11 (0.0%),29 (0.0%),3 ± 2 (2–6)
Altzaga,7 (0.0%),29 (0.0%),4 ± 4 (2–11)

## BY CNAE

In [22]:
analyse_trends(
    df_combined_filtered,
    category="group",
    variables=["Employees"],
    sort_by="Employees"
)

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  TERTIARY (NON-OFFICES) AND SERVICES
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                    11,828 (19.6%)                12,229 (20.5%)                12,342 (21.0%)                12,497 (21.8%)                12,833 (22.6%)                12,837 (23.2%)
  Growth                                              —                       🟢↑ 3.4%                       🟢↑ 0.9%                       🟢↑ 1.3%                       🟢↑ 2.7%                       🟢↑ 0.0%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                               93541.0 (23.7%)               95386.0 (23.8%)               97411.0 (23.6%)              100597.0 (23.6%)              102095.0 (24.1%)              106223.0 (24.3%)
  Mean ± SD                                  7.9 ± 28.7                    7.8 ± 28.4                    7.9 ± 28.4                    8.0 ± 28.9                    8.0 ± 29.1                    8.3 ± 30.4
  Q5–Q95                                       2.0–19.0                      2.0–19.0                      2.0–19.0                      2.0–19.0                      2.0–19.0                      2.0–49.0
  Growth                                              —                       🟢↑ 2.0%                       🟢↑ 2.1%                       🟢↑ 3.3%                       🟢↑ 1.5%                       🟢↑ 4.0%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  PRIMARY AND INTERMEDIATE PRODUCTS
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      4,663 (7.7%)                  4,513 (7.6%)                  4,378 (7.4%)                  4,207 (7.3%)                  4,156 (7.3%)                  4,020 (7.3%)
  Growth                                              —                       🔴↓ 3.2%                       🔴↓ 3.0%                       🔴↓ 3.9%                       🔴↓ 1.2%                       🔴↓ 3.3%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                               86900.0 (22.0%)               86716.0 (21.6%)               89058.0 (21.6%)               92963.0 (21.8%)               91645.0 (21.6%)               93533.0 (21.4%)
  Mean ± SD                                 18.6 ± 54.5                   19.2 ± 54.9                   20.3 ± 55.1                   22.1 ± 59.2                   22.1 ± 59.2                   23.3 ± 62.3
  Q5–Q95                                       2.0–99.0                      2.0–99.0                      2.0–99.0                      2.0–99.0                      2.0–99.0                      2.0–99.0
  Growth                                              —                       🔴↓ 0.2%                       🟢↑ 2.7%                       🟢↑ 4.4%                       🔴↓ 1.4%                       🟢↑ 2.1%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  OFFICES
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                    10,979 (18.2%)                11,236 (18.9%)                11,325 (19.2%)                11,126 (19.4%)                11,062 (19.5%)                10,880 (19.7%)
  Growth                                              —                       🟢↑ 2.3%                       🟢↑ 0.8%                       🔴↓ 1.8%                       🔴↓ 0.6%                       🔴↓ 1.6%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                               70112.0 (17.8%)               74789.0 (18.6%)               78178.0 (18.9%)               81818.0 (19.2%)               80926.0 (19.1%)               84745.0 (19.4%)
  Mean ± SD                                  6.4 ± 26.8                    6.7 ± 28.3                    6.9 ± 29.2                    7.4 ± 30.7                    7.3 ± 29.7                    7.8 ± 32.1
  Q5–Q95                                       2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–19.0                      2.0–19.0                      2.0–19.0
  Growth                                              —                       🟢↑ 6.7%                       🟢↑ 4.5%                       🟢↑ 4.7%                       🔴↓ 1.1%                       🟢↑ 4.7%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  HOTELS, RESTAURANTS, CAFÉS
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      4,402 (7.3%)                  4,419 (7.4%)                  4,474 (7.6%)                  4,456 (7.8%)                  4,420 (7.8%)                  4,447 (8.0%)
  Growth                                              —                       🟢↑ 0.4%                       🟢↑ 1.2%                       🔴↓ 0.4%                       🔴↓ 0.8%                       🟢↑ 0.6%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                23267.0 (5.9%)                24993.0 (6.2%)                27578.0 (6.7%)                29239.0 (6.9%)                27864.0 (6.6%)                31018.0 (7.1%)
  Mean ± SD                                  5.3 ± 14.2                    5.7 ± 15.0                    6.2 ± 15.2                    6.6 ± 15.6                    6.3 ± 14.7                    7.0 ± 16.4
  Q5–Q95                                       2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–19.0                      2.0–14.0                      2.0–19.0
  Growth                                              —                       🟢↑ 7.4%                      🟢↑ 10.3%                       🟢↑ 6.0%                       🔴↓ 4.7%                      🟢↑ 11.3%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  CONSTRUCTION INDUSTRY
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                     7,623 (12.6%)                 7,244 (12.2%)                 7,059 (12.0%)                 6,662 (11.6%)                 6,597 (11.6%)                 6,264 (11.3%)
  Growth                                              —                       🔴↓ 5.0%                       🔴↓ 2.6%                       🔴↓ 5.6%                       🔴↓ 1.0%                       🔴↓ 5.0%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                25581.0 (6.5%)                24261.0 (6.0%)                23761.0 (5.8%)                24251.0 (5.7%)                24665.0 (5.8%)                24695.0 (5.7%)
  Mean ± SD                                   3.4 ± 8.7                     3.3 ± 8.8                     3.4 ± 8.1                     3.6 ± 9.3                     3.7 ± 9.8                     3.9 ± 9.2
  Q5–Q95                                        2.0–9.0                       2.0–9.0                       2.0–9.0                       2.0–9.0                       2.0–9.0                       2.0–9.0
  Growth                                              —                       🔴↓ 5.2%                       🔴↓ 2.1%                       🟢↑ 2.1%                       🟢↑ 1.7%                       🟢↑ 0.1%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  TRANSPORT AND WAREHOUSING
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      3,711 (6.1%)                  3,516 (5.9%)                  3,450 (5.9%)                  3,297 (5.7%)                  3,215 (5.7%)                  3,167 (5.7%)
  Growth                                              —                       🔴↓ 5.3%                       🔴↓ 1.9%                       🔴↓ 4.4%                       🔴↓ 2.5%                       🔴↓ 1.5%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                19124.0 (4.9%)                19737.0 (4.9%)                19921.0 (4.8%)                21332.0 (5.0%)                20759.0 (4.9%)                21536.0 (4.9%)
  Mean ± SD                                  5.2 ± 19.4                    5.6 ± 20.9                    5.8 ± 22.0                    6.5 ± 25.3                    6.5 ± 24.3                    6.8 ± 25.3
  Q5–Q95                                       2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–19.0
  Growth                                              —                       🟢↑ 3.2%                       🟢↑ 0.9%                       🟢↑ 7.1%                       🔴↓ 2.7%                       🟢↑ 3.7%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  WHOLESALE
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      3,719 (6.2%)                  3,557 (6.0%)                  3,473 (5.9%)                  3,267 (5.7%)                  3,173 (5.6%)                  2,953 (5.3%)
  Growth                                              —                       🔴↓ 4.4%                       🔴↓ 2.4%                       🔴↓ 5.9%                       🔴↓ 2.9%                       🔴↓ 6.9%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                19067.0 (4.8%)                18898.0 (4.7%)                19688.0 (4.8%)                19845.0 (4.7%)                19784.0 (4.7%)                19455.0 (4.5%)
  Mean ± SD                                  5.1 ± 12.2                    5.3 ± 12.5                    5.7 ± 15.5                    6.1 ± 14.0                    6.2 ± 16.1                    6.6 ± 16.8
  Q5–Q95                                       2.0–14.0                      2.0–14.0                      2.0–14.0                      2.0–19.0                      2.0–19.0                      2.0–19.0
  Growth                                              —                       🔴↓ 0.9%                       🟢↑ 4.2%                       🟢↑ 0.8%                       🔴↓ 0.3%                       🔴↓ 1.7%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  SPECIALIZED RETAIL
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   2014                          2016                          2018                          2020                          2022                          2024
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Count                                      5,718 (9.5%)                  5,556 (9.3%)                  5,183 (8.8%)                  4,718 (8.2%)                  4,445 (7.8%)                  4,201 (7.6%)
  Growth                                              —                       🔴↓ 2.8%                       🔴↓ 6.7%                       🔴↓ 9.0%                       🔴↓ 5.8%                       🔴↓ 5.5%
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Employees                                18924.0 (4.8%)                18522.0 (4.6%)                18253.0 (4.4%)                17301.0 (4.1%)                16328.0 (3.9%)                16201.0 (3.7%)
  Mean ± SD                                   3.3 ± 9.1                     3.3 ± 8.0                     3.5 ± 8.4                     3.7 ± 8.8                     3.7 ± 8.3                     3.9 ± 8.0
  Q5–Q95                                        2.0–9.0                       2.0–9.0                       2.0–9.0                       2.0–9.0                       2.0–9.0                       2.0–9.0
  Growth                                              —                       🔴↓ 2.1%                       🔴↓ 1.5%                       🔴↓ 5.2%                       🔴↓ 5.6%                       🔴↓ 0.8%
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════


In [23]:
grouped_summary(
    df_combined_filtered[df_combined_filtered["Year"] == 2024],
    group_col="group",
    variables=["Employees"],
    sort_by='Count'
)

,Count (%),Employees (%),Mean Employees per establishment ± SD (q5–q95)
group,,,
Tertiary (non-offices) and services,"12,837 (23.2%)","106,223 (24.3%)",8 ± 30 (2–49)
Offices,"10,880 (19.7%)","84,745 (19.4%)",8 ± 32 (2–19)
Construction industry,"6,264 (11.3%)","24,695 (5.7%)",4 ± 9 (2–9)
"Hotels, restaurants, cafés","4,447 (8.0%)","31,018 (7.1%)",7 ± 16 (2–19)
Specialized retail,"4,201 (7.6%)","16,201 (3.7%)",4 ± 8 (2–9)
Primary and intermediate products,"4,020 (7.3%)","93,533 (21.4%)",23 ± 62 (2–99)
Transport and warehousing,"3,167 (5.7%)","21,536 (4.9%)",7 ± 25 (2–19)
Wholesale,"2,953 (5.3%)","19,455 (4.5%)",7 ± 17 (2–19)
Food and non-fragile retail,"1,748 (3.2%)","13,187 (3.0%)",8 ± 21 (2–49)
Craftsmen,"1,682 (3.0%)","10,617 (2.4%)",6 ± 24 (2–14)
Agriculture,"1,402 (2.5%)","4,090 (0.9%)",3 ± 4 (2–5)
Food and basic goods retail,"1,019 (1.8%)","3,392 (0.8%)",3 ± 2 (2–9)
Pharmacies,292 (0.5%),"1,627 (0.4%)",6 ± 4 (2–9)
Chemical industry,179 (0.3%),"6,345 (1.5%)",35 ± 70 (2–99)
Street trading,162 (0.3%),333 (0.1%),2 ± 0 (2–2)