In [2]:
import os
os.chdir('..')

In [3]:
import pandas as pd

# Import processed establishments

In [4]:
df = pd.read_csv('data/processed/establishments.csv', sep=',', decimal='.', encoding='utf-8')

In [5]:
df

,ID,Name,Municipality,CNAE,EMPLEST,x,y,Year,sector,group,Employees
0,L0000074,CAF,Beasain,3020,10,566017.911586,4.766770e+06,2014,Primary and intermediate products,Primary and intermediate products,500
1,L0000075,CAF,Irun,3020,9,596812.041848,4.799328e+06,2014,Primary and intermediate products,Primary and intermediate products,499
2,L0000084,Goenaga,Zaldibia,4672,2,569178.939506,4.765813e+06,2014,Wholesale,Wholesale,5
3,L0000090,Aquarbe,Zumarraga,3600,2,555801.318749,4.771036e+06,2014,Primary and intermediate products,Primary and intermediate products,5
4,L0000105,Ayestaran Ferreteria,Donostia / San Sebastián,4674,2,583245.088260,4.796927e+06,2014,Wholesale,Wholesale,5
...,...,...,...,...,...,...,...,...,...,...,...
348123,L0555718,Aloe Loredenda,Urnieta,4776,1,581859.769927,4.789023e+06,2024,Food and non-fragile consumer goods,Food and non-fragile retail,2
348124,L0555725,Norbide,Donostia / San Sebastián,8299,2,582001.821087,4.795791e+06,2024,Offices,Offices,5
348125,L0555726,Limpiezas Soldene,Donostia / San Sebastián,8121,6,580440.289061,4.795635e+06,2024,Offices,Offices,49
348126,L0555727,Asoc. Benefica Asistencial Elkarbanatuz,Irun,9499,3,597331.818643,4.798751e+06,2024,Offices,Offices,9
348127,L0555731,Fontanería,Errezil,4322,1,566895.467320,4.779580e+06,2024,Construction industry,Construction industry,2

# Calculate FTG

In [6]:
from utils.models import apply_establishment_demand_model

apply_establishment_demand_model(df, sector_col= 'sector', employee_col='Employees')

,ID,Name,Municipality,CNAE,EMPLEST,x,y,Year,sector,group,Employees,ftg
0,L0000074,CAF,Beasain,3020,10,566017.911586,4.766770e+06,2014,Primary and intermediate products,Primary and intermediate products,500,131.52
1,L0000075,CAF,Irun,3020,9,596812.041848,4.799328e+06,2014,Primary and intermediate products,Primary and intermediate products,499,131.27
2,L0000084,Goenaga,Zaldibia,4672,2,569178.939506,4.765813e+06,2014,Wholesale,Wholesale,5,22.14
3,L0000090,Aquarbe,Zumarraga,3600,2,555801.318749,4.771036e+06,2014,Primary and intermediate products,Primary and intermediate products,5,7.77
4,L0000105,Ayestaran Ferreteria,Donostia / San Sebastián,4674,2,583245.088260,4.796927e+06,2014,Wholesale,Wholesale,5,22.14
...,...,...,...,...,...,...,...,...,...,...,...,...
348123,L0555718,Aloe Loredenda,Urnieta,4776,1,581859.769927,4.789023e+06,2024,Food and non-fragile consumer goods,Food and non-fragile retail,2,9.14
348124,L0555725,Norbide,Donostia / San Sebastián,8299,2,582001.821087,4.795791e+06,2024,Offices,Offices,5,3.67
348125,L0555726,Limpiezas Soldene,Donostia / San Sebastián,8121,6,580440.289061,4.795635e+06,2024,Offices,Offices,49,4.55
348126,L0555727,Asoc. Benefica Asistencial Elkarbanatuz,Irun,9499,3,597331.818643,4.798751e+06,2024,Offices,Offices,9,3.75
348127,L0555731,Fontanería,Errezil,4322,1,566895.467320,4.779580e+06,2024,Construction industry,Construction industry,2,6.99